COSC481W-2021Fall/capstone-adam-and-the-mod-squad

.gitignore.txt
Needs to be updated as project grows, especially merging in Django (etc) base .gitignore
=> added gitIgnore

.gitignore
Included frameworks and dependencies used; fixes issue #3
=> impl: Create .gitignore

mydjangoproject/muninn/admin.py, mydjangoproject/muninn/apps.py, mydjangoproject/muninn/models.py, mydjangoproject/muninn/tests.py, mydjangoproject/muninn/views.py, mydjangoproject/mydjangoproject/settings.py, mydjangoproject/mydjangoproject/urls.py
The setup for development in Django framework
=> setup of muninn app in django

mydjangoproject/mydjangoproject/settings.py
App name needed to be added to allow it to track changes to the app.
resolves: #17
=> fix: Migrations not working

mydjangoproject/mydjangoproject/settings.py, mydjangoproject/users/admin.py, mydjangoproject/users/apps.py, mydjangoproject/users/models.py, mydjangoproject/users/tests.py, mydjangoproject/users/views.py
Issue #19 
There are a couple of folders and an app that needed to be created for the various web pages to work and for registration and login/logout to work. Also needed to make a url.py in muninn for defining path directory.
What was changed:
-Created users app so we can do registration and login/logout
-Created templates folder in users with a folder inside called users so we can have html templates for registration and login/logout
-Created templates folder in muninn with a folder inside called muninn so we can have html templates for the various web pages
-Created urls.py in muninn for defining path directory
=> fix: Folder creation for templates and user

mydjangoproject/muninn/admin.py, mydjangoproject/muninn/models.py
not an issue but rather makes code easier to understand for front end
=> cleanup of models.py

mydjangoproject/muninn/templates/muninn/task_list.html
=> fix: add delete button

mydjangoproject/muninn/templates/muninn/about.html, mydjangoproject/muninn/templates/muninn/friends.html, mydjangoproject/muninn/templates/muninn/pet_shop.html, mydjangoproject/muninn/templates/muninn/roost.html, mydjangoproject/muninn/templates/muninn/statistics.html, mydjangoproject/muninn/templates/muninn/user_settings.html, mydjangoproject/muninn/urls.py, mydjangoproject/muninn/views.py
Issue: #40
added html files for all main blank pages
added the url paths and views
=> impl: add blank pages

mydjangoproject/muninn/static/muninn/styles.css, mydjangoproject/muninn/templates/muninn/base.html, mydjangoproject/muninn/templates/muninn/task_list.html
Added progress bar towards next level and stats displaying the user's current level and the amounts of XP and currency the user currently possesses. 
GitHub issue #46
=> Feature: Progress Bar and Stats

mydjangoproject/users/templates/users/register.html
- fixes an incorrect URL that would give  404 error upon clicking
- user now is able to switch from registration to login page easily if they have an account
fixes Issue #71
=> fix:  Account Link bug

mydjangoproject/muninn/static/muninn/styles.css, mydjangoproject/muninn/templates/muninn/message.html
Fixed the bug that main has where some of the CSS was missing. I added the CSS that was missing and made sure everything that needed to be there is there.
GitHub issue #81
=> bug:Sara clean up css bug

mydjangoproject/muninn/functions.py, mydjangoproject/muninn/templates/muninn/base.html, mydjangoproject/muninn/templates/muninn/task_list.html, mydjangoproject/muninn/views.py
Fixes Issue #66 ; connects backend/DB to the UI for dashboard and navbar
=> Jesse sakib connect back to front

mydjangoproject/muninn/static/muninn/styles.css, mydjangoproject/muninn/templates/muninn/pet_shop.html
Made registration popup fade
Adjusted Buy button
Fixed "Buy Pet" popup
GitHub issue #72
=> Style: jesse-sara-styling-bugs

mydjangoproject/muninn/static/muninn/styles.css, mydjangoproject/muninn/templates/muninn/base.html, mydjangoproject/muninn/templates/muninn/pet_shop.html, mydjangoproject/muninn/templates/muninn/roost.html, mydjangoproject/muninn/views.py
User is now able to view their pets in an orderly format, filter and search nicknames and animal names, and order by level.  They can select an animal to be shown in wide "stadium" view. 
- styles and orders animals
- creates ui for stadium
- filters and searches set up
- roost models connected and implemented
fixes Issue #68
=> impl: Roost page and functionalities

mydjangoproject/muninn/static/muninn/styles.css
-position of buttons changed
-position of pop up changed
resolves #90
=> fix: fix some styles for the pet shop

mydjangoproject/muninn/views.py
passed the user and level to all views
resolves #92
=> fix: sidebar not showing level and money

mydjangoproject/muninn/templates/muninn/base.html
-When on the roost page, the nav bar link for the roost will change color
GitHub issue: #104
=> style: Roost now lights up

mydjangoproject/muninn/static/muninn/styles.css, mydjangoproject/muninn/templates/muninn/friends.html, mydjangoproject/muninn/templates/muninn/task_list.html
-Got rid of the picture of Chiara in the progress bar
-Got rid of the friends page since we are not doing that.
GitHub issue: #105
=> style: Got rid of the picture of Chiara

mydjangoproject/muninn/templates/muninn/base.html
-Got rid of settings button
GitHub issue: #103
=> style: Got rid of Settings

mydjangoproject/muninn/static/muninn/styles.css, mydjangoproject/muninn/templates/muninn/about.html
-About me page buttons are now aligned no matter if you are logged in or not.
-Coffee button will take the user to another tab
GitHub issue: #94
=> Sara jesse fix about me buttons

mydjangoproject/muninn/templates/muninn/about.html, mydjangoproject/muninn/views.py
User W can now crowdfund the team because they love our work so much.
- linked account in the about me page
- 
Fixes #100
=> impl: Buy me a coffee acct

mydjangoproject/muninn/static/muninn/scripts.js, mydjangoproject/muninn/templates/muninn/task_list.html, mydjangoproject/muninn/views.py
Users can now modify existing tasks and habits. Resolves issue #99
=> Feature: Edit Tasks and Habits

mydjangoproject/muninn/views.py
-Level and gold shows up on side nav bar
Github issue: #125
=> bug: Fixed level and gold

mydjangoproject/muninn/views.py
Issue #97 ; added stick cat as an easter egg if current pet is named "Mr_J"
=> feature: added Stick Cat as an Easter Egg

mydjangoproject/muninn/templates/muninn/faq.html
- Added the info for editing a task
Github issue: #117
=> chore: Added info on editing task
